<?php
    return [
        'enabled'                => env('DEBUGBAR_ENABLED', NULL),
        'except'                 => [
            'telescope*',
            'horizon*',
        ],
        'storage'                => [
            'enabled'    => TRUE,
            'open'       => env('DEBUGBAR_OPEN_STORAGE', FALSE),
            'driver'     => 'file',
            'path'       => storage_path('debugbar'),
            'connection' => NULL,
            'provider'   => '',
            'hostname'   => '127.0.0.1',
            'port'       => 2304,
        ],
        'editor'                 => env('DEBUGBAR_EDITOR') ?: env('IGNITION_EDITOR', 'phpstorm'),
        'remote_sites_path'      => env('DEBUGBAR_REMOTE_SITES_PATH'),
        'local_sites_path'       => env('DEBUGBAR_LOCAL_SITES_PATH', env('IGNITION_LOCAL_SITES_PATH')),
        'include_vendors'        => TRUE,
        'capture_ajax'           => TRUE,
        'add_ajax_timing'        => FALSE,
        'ajax_handler_auto_show' => TRUE,
        'error_handler'          => FALSE,
        'clockwork'              => FALSE,
        'collectors'             => [
            'phpinfo'         => TRUE,
            'messages'        => TRUE,
            'time'            => TRUE,
            'memory'          => TRUE,
            'exceptions'      => TRUE,
            'log'             => TRUE,
            'db'              => TRUE,
            'views'           => TRUE,
            'route'           => TRUE,
            'auth'            => FALSE,
            'gate'            => TRUE,
            'session'         => TRUE,
            'symfony_request' => TRUE,
            'mail'            => TRUE,
            'laravel'         => FALSE,
            'events'          => FALSE,
            'default_request' => FALSE,
            'logs'            => FALSE,
            'files'           => FALSE,
            'config'          => FALSE,
            'cache'           => TRUE,
            'models'          => TRUE,
            'livewire'        => TRUE,
            'jobs'            => FALSE,
        ],
        'options'                => [
            'time'            => [
                'memory_usage' => FALSE,
            ],
            'messages'        => [
                'trace' => TRUE,
            ],
            'memory'          => [
                'reset_peak'    => FALSE,
                'with_baseline' => FALSE,
                'precision'     => 0,
            ],
            'auth'            => [
                'show_name' => TRUE,
            ],
            'db'              => [
                'with_params'             => TRUE,
                'backtrace'               => TRUE,
                'backtrace_exclude_paths' => [],
                'timeline'                => FALSE,
                'duration_background'     => TRUE,
                'explain'                 => [
                    'enabled' => FALSE,
                    'types'   => ['SELECT'],
                ],
                'hints'                   => FALSE,
                'show_copy'               => FALSE,
                'slow_threshold'          => FALSE,
                'memory_usage'            => FALSE,
                'soft_limit'              => 100,
                'hard_limit'              => 500,
            ],
            'mail'            => [
                'timeline'  => FALSE,
                'show_body' => TRUE,
            ],
            'views'           => [
                'timeline'      => FALSE,
                'data'          => FALSE,
                'group'         => 50,
                'exclude_paths' => [
                    'vendor/filament',
                ],
            ],
            'route'           => [
                'label' => TRUE,
            ],
            'session'         => [
                'hiddens' => [],
            ],
            'symfony_request' => [
                'hiddens' => [],
            ],
            'events'          => [
                'data' => FALSE,
            ],
            'logs'            => [
                'file' => NULL,
            ],
            'cache'           => [
                'values' => TRUE,
            ],
        ],
        'inject'                 => TRUE,
        'route_prefix'           => '_debugbar',
        'route_middleware'       => [],
        'route_domain'           => NULL,
        'theme'                  => env('DEBUGBAR_THEME', 'dark'),
        'debug_backtrace_limit'  => 50,
    ];
